### ISSUE TITLE
开机实例，需求，需要一个开机模版，另外已经创建的实例需要编辑功能

### ISSUE THREAD

**Issue by jin-gubang** [doubleDimple/oci-start#18]
创建实例：密码随机就好
快速选择模版：
1+6+50*2个
1+6+50*4个
2+12+50*2个
4+24+50*1个
可以考虑加一个自定义模版
间隔快速选择：
10s，30s，60s，200s，500s，1000s，自定义
实例编辑：修改上方模版和间隔

**Comment by doubleDimple** [comment]
done
