### ISSUE TITLE
页面经常出错，Whitelabel Error Page

### ISSUE THREAD

**Issue by AshinLin** [doubleDimple/oci-start#27]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Nov 23 18:55:25 UTC 2024
There was an unexpected error (type=Not Found, status=404).
<img width="691" alt="image" src="https://github.com/user-attachments/assets/cbc2b552-411a-4016-828c-b20269fced8c">

**Comment by doubleDimple** [comment]
get

**Comment by doubleDimple** [comment]
已修复,请更新最新版本v-2.0.1,有问题,请再次反馈

**Comment by doubleDimple** [comment]
done
