### ISSUE TITLE
[需求]新增api的文本框太多了,而且顺序也比较混乱

### ISSUE THREAD

**Issue by jin-gubang** [doubleDimple/oci-start#6]
[需求]新增api的文本框太多了,而且顺序也比较混乱
目标:
1.api名称:自定义api的名称,必填,不可重复
2.粘贴oci获取的api密钥:必填,直接全文粘贴到文本框即可
2.1.自动忽略key_file部分
3.上传key_file

**Comment by jin-gubang** [comment]
另外,为什么现在需要租户id呢?感觉有些麻烦了

**Comment by doubleDimple** [comment]
done
